# Generated by Django 6.0.6 on 2026-06-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='testimonials/default-avatar.png', null=True, upload_to='testimonials/'),
        ),
    ]
