# Generated by Django 6.0.6 on 2026-06-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_solutions', '0003_companyhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyHistory',
        ),
    ]
